#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

#group1:
#  group_name: base
#  component_name: base
#  buttons: [[stop,stop,omni],
#    [init,trigger,init],
#    [recover,trigger,recover]]
group4:
  group_name: sensorring
  component_name: sensorring
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [front,move,front],
    [back,move,back],
    [left,move,left],
    [right,move,right]]
group5:
  group_name: arm_left
  component_name: arm_left
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [home,move,home],
    [folded,move,folded],
    [side,move,side]]
group6:
  group_name: arm_right
  component_name: arm_right
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [home,move,home],
    [folded,move,folded],
    [side,move,side]]
group7:
  group_name: 'BORING / WOMEN / RUN'
  component_name: cobvid
  buttons: [
    ['BR -> (1) ARMS', trigger ,br1],
    [(1) SLENDER, trigger, sc1],
    ['BR -> (2) ARMS', trigger, br2],
    ['(2) WINDOW', trigger, sc2],
    ['BR -> (3)', trigger, br3],
    ['* (3) WOMEN', trigger, sc3],
    ['BR -> (4) ARMS', trigger, br4],
    ['(4) RUN AWAY', trigger, sc4],
    ]
group8:
  group_name: 'ROSE / PRESENT'
  component_name: cobvid
  buttons: [
    ['CAL -> (5) A R ROSE', trigger, cal5],
    ['BR -> (5) A R H', trigger, br5],
    ['(5) GRIP ROSE', trigger, sc5],
    ['BR -> (6) ARM', trigger, br6],
    ['(6) THE PRESENT', trigger, sc6],
    ]
group9:
  group_name: 'SCENE CHEERING'
  component_name: cobvid
  buttons: [
    [BR -> (7) ARMS, trigger, br7],
    [(7) ARMS-UP, trigger, sc7],
    ['BR -> (8)', trigger, br8],
    ['(8) 360° ROT', trigger, sc8],
    ['BR -> (9) ARMS', trigger, br9],
    ['(9) DRUMS', trigger, sc9],
    ['BR -> (10) ALL', trigger, br10],
    ['(10) CORNER', trigger, sc10],
    ]
group91:
  group_name: 'SCENE'
  component_name: cobvid
  buttons: [
    ['BR -> (11) MIMIC', trigger, br11],
    ['(11) ENDING', trigger, sc11],
    ['!!! TEST MIMIC !!!', trigger, test1],
    ['!!! TEST LED !!!', trigger, test2],
    ['!!! TEST GRIPPER !!!', trigger, test3],
    ]
group92:
  group_name: 'ENABLE CTRL'
  component_name: cobvid
  buttons: [
    ['restart', trigger, restart],
    ['FAKERUN', trigger, enable_fakerun],
    ['BASE', trigger, enable_base],
    ['ARM LEFT', trigger, enable_arm_left],
    ['ARM RIGHT', trigger, enable_arm_right],
    ['GRIPPER LEFT', trigger, enable_gripper_left],
    ['GRIPPER RIGHT', trigger, enable_gripper_right],
    ['MIMIC', trigger, enable_mimic],
    ['LED', trigger, enable_led],
    ]
group93:
  group_name: 'DISABLE CTRL'
  component_name: cobvid
  buttons: [
    ['status', trigger, status],
    ['FAKERUN', trigger, disable_fakerun],
    ['BASE', trigger, disable_base],
    ['ARM LEFT', trigger, disable_arm_left],
    ['ARM RIGHT', trigger, disable_arm_right],
    ['GRIPPER LEFT', trigger, disable_gripper_left],
    ['GRIPPER RIGHT', trigger, disable_gripper_right],
    ['MIMIC', trigger, disable_mimic],
    ['LED', trigger, disable_led],
    ]
group98:
  group_name: 'L GRIPPER'
  component_name: gripper_left
  buttons: [
    ['recover', trigger, recover],
    ['home', move, home],
    ['open', move, open],
    ['close', move, close],
    ]
group99:
  group_name: 'R GRIPPER'
  component_name: gripper_right
  buttons: [
    ['recover', trigger, recover],
    ['home', move, home],
    ['open', move, open],
    ['close', move, close],
    ]
