group75:
  group_name: 'POSE'
  component_name: cobvid
  buttons: [
    ['(1) DEMO ARMS SIDE', trigger, po1],
    ['(2) CHEER ARMS UP', trigger, po2],
    ['(3) CHEER ARMS TURN', trigger, po3],
    ]
group77:
  group_name: 'DEMO'
  component_name: cobvid
  buttons: [
    ['P PRE BALL START', trigger, po1],
    ['TF HOLD BALL', trigger, br1],
    ['TF Z', trigger, sc1],
    ['TF ROLL', trigger, sc2],
    ['TF CROSS YZ', trigger, sc3],
    ['TF CIRC 8 YZ', trigger, sc4],
    ['TF MP CIRC XY/Yaw', trigger, sc5],
    ['TF SCX', trigger, scx],
    ]
group78:
  group_name: 'PLAY GOAL'
  component_name: cobvid
  buttons: [
    ['P PRE BALL START', trigger, po1],
    ['HOLDBALL', trigger, rec1],
    ['Z', trigger, rec2],
    ['ROLL', trigger, rec3],
    ['CROSS', trigger, rec4],
    ['CIRC 8', trigger, rec5],
    ['ALL', trigger, recx],
    ['ALL NO ROLL', trigger, recnr],
    ['EXPD', trigger, recxx],
    ['LED', trigger, led],
    ]
group79:
  group_name: 'TEST'
  component_name: cobvid
  buttons: [
    ['move goal', trigger, test1],
    ['move vel', trigger, test2],
    ['repeat combine', trigger, test3],
    ['play goal', trigger, test4],
    ['ball start', trigger, test5],
    ['GET FRAME', trigger, test9],
    ]